version: '3.8'

services:

  traefik:
    image: ghcr.io/silkkycloud/traefik:2.5.4
    command: --configFile=/etc/traefik/traefik.yml
    hostname: traefik
    networks:
      - socat_net
      - metrics_net
      - public
    ports:
      # X-Forwarded-For / X-Real-IP headers are only available in host mode.
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - "node.labels.reverse_proxy == true"
      update_config:
        parallelism: 1
        failure_action: rollback
      labels:
        # Prometheus
        - "prometheus-job=traefik"
        - "prometheus-port=8082"
        - "prometheus-path=/metrics"
        # Traefik
        - "traefik.enable=true"
        # Router
        - "traefik.http.routers.traefik.rule=Host(`traefik.silkky.cloud`)"
        - "traefik.http.routers.traefik.entrypoints=websecure"
        - "traefik.http.routers.traefik.tls=true"
        - "traefik.http.routers.traefik.middleware=authentik-proxy@docker"
        - "traefik.http.routers.traefik.service=traefik-service"
        # Service
        - "traefik.http.services.traefik-service.loadbalancer.server.port=8080"
    configs:
      - source: traefik-static
        target: /etc/traefik/traefik.yml
      - source: traefik-dynamic
        target: /etc/traefik/dynamic.yml
    secrets:
      # Origin certificates
      - source: cloudflare-origin-crt
        target: origin.crt
      - source: piped-cloudflare-origin-crt
        target: piped.crt
      # Origin keys
      - source: cloudflare-origin-key
        target: origin.key
        mode: 0600
      - source: piped-cloudflare-origin-key
        target: piped.key
        mode: 0600

  dockersocat:
    image: ghcr.io/tecnativa/docker-socket-proxy:0.1
    networks:
      - socat_net
    logging:
      driver: none
    deploy:
      mode: global
      placement:
        constraints:
          - "node.role == manager"
      resources:
        reservations:
          memory: 5M
          cpus: '0.05'
        limits:
          memory: 25M
          cpus: '0.1'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NETWORKS=1
      - SERVICES=1
      - TASKS=1

networks:
  # Create:
  # docker network create \
  #   --driver overlay \
  #   --subnet 20.0.0.0/16 \
  #   --opt com.docker.network.driver.mtu=1450 \
  #   --opt encrypted=true \
  #   public
  public:
    external: true
  metrics_net:
    external: true
  socat_net:
    driver: overlay
    internal: true
    driver_opts:
      encrypted: "true"
      com.docker.network.driver.mtu: 1450

configs:
  traefik-static:
    file: ./traefik/traefik.yml
  traefik-dynamic:
    file: ./traefik/dynamic.yml

secrets:
  # Origin certificates
  cloudflare-origin-crt:
    external: true
  piped-cloudflare-origin-crt:
    external: true
  # Origin keys
  cloudflare-origin-key:
    external: true
  piped-cloudflare-origin-key:
    external: true