version: '3.8'

services:

  caddy:
    image: ghcr.io/silkkycloud/core-caddy:latest
    hostname: caddy
    networks:
      - public
    ports:
      # X-Forwarded-For / X-Real-IP headers are only available in host mode.
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - "node.labels.proxy == true"
    volumes:
      - caddy_tls:/tls
    environment:
      # OAuth for administrator applications
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}

networks:
  # Create: docker network create --subnet 10.10.0.0/16 -d overlay public
  public:
    external: true

volumes:
  # Needed for Cloudflare origin certificates
  # Create: docker volume create caddy_tls
  caddy_tls:
    external: true
