version: '3.8'

services:

  agent:
    image: portainer/agent:2.10.0-alpine
    networks:
      - agent_net
    deploy:
      mode: global
      placement:
        constraints:
          - "node.platform.os == linux"
          - "node.role == manager"
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 512M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

  portainer:
    image: portainer/portainer-ce:2.9.2-alpine
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    networks:
      - agent_net
      - public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.role == manager"
          - "node.hostname == main-1"
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 1.5G
    volumes:
      - portainer_data:/data

networks:
  agent_net:
    driver: overlay
    attachable: true
    
  public:
    external: true

volumes:
  portainer_data: