version: '3.8'

services:

  caddy:
    image: ghcr.io/silkkycloud/caddy:latest
    hostname: caddy
    networks:
      - public
    ports:
      # X-Forwarded-For / X-Real-IP headers are only available in host mode.
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - "node.labels.proxy == true"
      resources:
        limits:
          cpus: "8"
          memory: 6G
        reservations:
          cpus: "1"
          memory: 1G
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - caddy_tls:/tls
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile

  portainer:
    image: portainer/portainer-ce:2.9.2-alpine
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    hostname: portainer
    networks:
      - public
      - agent
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.hostname == main-1"
          - "node.role == manager"
      resources:
        limits:
          cpus: "2"
          memory: 1.5G
        reservations:
          cpus: "0.5"
          memory: 500M
    volumes:
      - portainer_data:/data

  agent:
    image: portainer/agent:2.9.2-alpine
    networks:
      - agent
    deploy:
      mode: global
      placement:
        constraints:
          - "node.role == manager"
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.3"
          memory: 256M

networks:
  # Create: docker network create --subnet 10.10.0.0/16 -d overlay public
  public:
    external: true

  agent:
    driver: overlay
    attachable: true

volumes:
  caddy_data:
  caddy_config:
  # Needed for Cloudflare origin certificates
  # Create: docker volume create caddy_tls
  caddy_tls:
    external: true

  portainer_data:

configs:
  caddyfile:
    file: ./Caddyfile
