theme: dark

log:
  level: info

server:
  host: 0.0.0.0
  port: 9091

notifier:
  smtp:
    host: smtp.eu.mailgun.org
    port: 587
    username: noreply@robot.silkky.cloud
    sender: "Authelia <noreply@rebot.silkky.cloud>"
    subject: "[Authelia] {title}"

regulation:
  max_retries: 3
  find_time: 5m
  ban_time: 15m

storage:
  local:
    path: /data/db.sqlite3

session:
  domain: silkky.cloud
  expiration: 4h
  redis:
    host: redis
    port: 6379

authentication_backend:
  file:
    path: /data/users.yml
    password:
      algorithm: argon2id