global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  # Create a job for Docker daemons.
  - job_name: 'docker'
    dockerswarm_sd_configs:
      - host: tcp://tasks.dockersocat:2375
        role: nodes
    static_configs:
      # Fetch metrics on port 9323.
      - targets: ['10.0.1.1:9323']
        labels:
          instance: 'main-1'
      - targets: ['10.0.1.2:9323']
        labels:
          instance: 'main-2'
      - targets: ['10.0.1.3:9323']
        labels:
          instance: 'main-3'

  # Create a job for Docker Swarm containers.
  - job_name: 'dockerswarm'
    dockerswarm_sd_configs:
      - host: tcp://tasks.dockersocat:2375
        role: tasks
    relabel_configs:
      # Only keep containers that should be running.
      - source_labels: [__meta_dockerswarm_task_desired_state]
        regex: running
        action: keep
      # Only keep containers that have a `prometheus-job` label.
      - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
        regex: .+
        action: keep
      # Use the task labels that are prefixed by `prometheus-`.
      - regex: __meta_dockerswarm_service_label_prometheus_(.+)
        action: labelmap
        replacement: $1
