# Deploy using Compose
version: '3.8'

services:

  wireguard:
    image: ghcr.io/linuxserver/wireguard
    restart: always
    container_name: wireguard
    hostname: wireguard
    ports:
      - ${WIREGUARD_PORT}:51820/udp
    volumes:
      - config:/config
      - /lib/modules:/lib/modules
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
      - SERVERPORT=${WIREGUARD_PORT}
      - PEERS=${WIREGUARD_PEERS}
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

volumes:
  config: